version: '2.0'

services:

  atcoi-dev:
    # container_name: atcoi-dev
    image: 
    build:
      context: .
      dockerfile: dockerfile-dev
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=development
