version: '2.0'

services:

  atcoi-prod:
    image: atcoi/profilemgr-ui:latest
    
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - '80:80'
    environment:
      - NODE_ENV=development